version: '3'

services:

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - backbone
    restart: always
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "16543:80"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - backbone
    restart: always

  frontend:
    volumes:
      - ./frontend:/app
    build: 
      context: ./frontend
      dockerfile: ./frontend.dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - backbone


  backend:
    volumes:
      - ./backend:/app
    build: 
      context: ./backend
      dockerfile: ./backend.dockerfile
    container_name: backend
    ports:
      - "4000:4000"
      - "4242:4242"
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - backbone


networks:
  backbone:
    driver: bridge

